import { useMemo, useState } from "react";
import { IonBadge, IonButton, IonIcon, IonInput, IonItem, IonLabel, IonModal, IonSelect, IonSelectOption, IonSpinner, IonTextarea, IonToast } from "@ionic/react";
import { addOutline, callOutline, checkmarkOutline, closeOutline, refreshOutline } from "ionicons/icons";
import { PageFeedback } from "../components/page-feedback";
import { PageHeading } from "../components/page-heading";
import { useApiResource } from "../hooks/use-api-resource";
import { ApiError, apiRequest } from "../lib/api";
import { formatDate, isOverdue } from "../lib/format";
import { recordId, type Lead, type LeadStage } from "../types";

const stages: Record<LeadStage, string> = { NEW: "جدید", CONTACTED: "تماس گرفته شد", QUALIFIED: "واجد شرایط", PROPOSAL: "پیشنهاد ارسال شد", NEGOTIATION: "مذاکره", WON: "برنده", LOST: "از دست‌رفته" };
const sources = ["WEBSITE", "INSTAGRAM", "REFERRAL", "PHONE", "EXHIBITION", "OTHER"];
const sourceLabels: Record<string, string> = { WEBSITE: "وب‌سایت", INSTAGRAM: "اینستاگرام", REFERRAL: "معرفی", PHONE: "تماس تلفنی", EXHIBITION: "نمایشگاه", OTHER: "سایر" };

export function LeadsPage({ token }: { token: string }) {
  const resource = useApiResource<Lead[]>("/leads", token);
  const [createOpen, setCreateOpen] = useState(false); const [followUpLead, setFollowUpLead] = useState<Lead>(); const [filter, setFilter] = useState<LeadStage | "ALL">("ALL"); const [message, setMessage] = useState<string>();
  const leads = resource.data ?? [];
  const visible = useMemo(() => filter === "ALL" ? leads : leads.filter((lead) => lead.stage === filter), [leads, filter]);
  const replace = (updated: Lead) => resource.setData((items) => (items ?? []).map((item) => recordId(item) === recordId(updated) ? updated : item));
  const pendingCount = leads.flatMap((lead) => lead.followUps ?? []).filter((item) => item.status === "PENDING" && isOverdue(item.dueAt)).length;
  return <>
    <PageHeading eyebrow="CRM و فروش" title="لیدها و پیگیری فروش" description={`${pendingCount.toLocaleString("fa-IR")} پیگیری معوق دارید. هر لید از اولین تماس تا نتیجه در همین صفحه می‌ماند.`} action={<div className="page-action-group"><IonButton fill="outline" onClick={() => void resource.reload()}><IonIcon slot="icon-only" icon={refreshOutline} /></IonButton><IonButton onClick={() => setCreateOpen(true)}><IonIcon slot="start" icon={addOutline} />لید جدید</IonButton></div>} />
    <div className="lead-filters">{(["ALL", ...Object.keys(stages)] as Array<LeadStage | "ALL">).map((stage) => <button key={stage} className={filter === stage ? "active" : ""} onClick={() => setFilter(stage)}>{stage === "ALL" ? "همه" : stages[stage]}</button>)}</div>
    <PageFeedback loading={resource.loading} error={resource.error} empty={!resource.loading && !resource.error && !visible.length} emptyTitle="هنوز لیدی ثبت نشده" emptyDescription="اولین سرنخ فروش را ثبت کنید." onRetry={() => void resource.reload()}><section className="lead-grid">{visible.map((lead) => { const next = (lead.followUps ?? []).filter((follow) => follow.status === "PENDING").sort((a,b) => +new Date(a.dueAt) - +new Date(b.dueAt))[0]; return <article className="lead-card" key={recordId(lead)}><div className="lead-card-head"><div><h2>{lead.name}</h2><p>{lead.companyName || "مشتری شخصی"} · {sourceLabels[lead.source] || lead.source}</p></div><IonBadge className={`lead-stage stage-${lead.stage.toLowerCase()}`}>{stages[lead.stage] || lead.stage}</IonBadge></div><div className="customer-contact"><IonIcon icon={callOutline} />{lead.mobile || "شماره تماس ثبت نشده"}</div><p className="lead-note">{lead.notes || "یادداشتی ثبت نشده"}</p><div className="lead-card-footer"><span className={next && isOverdue(next.dueAt) ? "overdue" : ""}>پیگیری: {formatDate(next?.dueAt, true)}</span><IonButton size="small" fill="outline" onClick={() => setFollowUpLead(lead)}><IonIcon slot="start" icon={addOutline} />پیگیری</IonButton></div>{next ? <div className="lead-follow-up-line"><span>{next.note || "بدون توضیح"}</span>{next.status === "PENDING" && <IonButton fill="clear" size="small" onClick={() => void apiRequest<Lead>(`/leads/${recordId(lead)}/follow-ups/${recordId(next)}`, { method: "PATCH", token }).then(replace).catch(() => setMessage("تکمیل پیگیری ممکن نشد."))}><IonIcon slot="icon-only" icon={checkmarkOutline} /></IonButton>}</div> : null}</article>; })}</section></PageFeedback>
    <CreateLeadModal isOpen={createOpen} token={token} onDismiss={() => setCreateOpen(false)} onCreated={(lead) => { resource.setData((items) => [lead, ...(items ?? [])]); setCreateOpen(false); }} />
    <FollowUpModal lead={followUpLead} token={token} onDismiss={() => setFollowUpLead(undefined)} onSaved={(lead) => { replace(lead); setFollowUpLead(undefined); }} />
    <IonToast isOpen={Boolean(message)} message={message} color="danger" duration={2500} onDidDismiss={() => setMessage(undefined)} />
  </>;
}

function CreateLeadModal({ isOpen, token, onDismiss, onCreated }: { isOpen: boolean; token: string; onDismiss: () => void; onCreated: (lead: Lead) => void }) {
  const [name,setName]=useState(""); const [mobile,setMobile]=useState(""); const [companyName,setCompanyName]=useState(""); const [source,setSource]=useState("WEBSITE"); const [stage,setStage]=useState<LeadStage>("NEW"); const [notes,setNotes]=useState(""); const [saving,setSaving]=useState(false);
  async function submit(e: React.FormEvent) { e.preventDefault(); setSaving(true); try { const lead = await apiRequest<Lead>("/leads", { method:"POST", token, body:{ name:name.trim(), mobile:mobile.trim() || undefined, companyName:companyName.trim() || undefined, source, stage, notes:notes.trim() || undefined } }); setName("");setMobile("");setCompanyName("");setSource("WEBSITE");setStage("NEW");setNotes(""); onCreated(lead); } finally { setSaving(false); } }
  return <IonModal isOpen={isOpen} onDidDismiss={onDismiss} className="form-modal"><div className="modal-shell"><div className="modal-heading"><div><span className="page-eyebrow">SALES PIPELINE</span><h2>ثبت لید جدید</h2></div><IonButton fill="clear" onClick={onDismiss}><IonIcon slot="icon-only" icon={closeOutline} /></IonButton></div><form className="modal-form" onSubmit={submit}><IonItem className="form-item" lines="none"><IonLabel position="stacked">نام لید</IonLabel><IonInput required value={name} onIonInput={e=>setName(e.detail.value??"")} /></IonItem><div className="form-grid"><IonItem className="form-item" lines="none"><IonLabel position="stacked">موبایل</IonLabel><IonInput type="tel" value={mobile} onIonInput={e=>setMobile(e.detail.value??"")} /></IonItem><IonItem className="form-item" lines="none"><IonLabel position="stacked">شرکت</IonLabel><IonInput value={companyName} onIonInput={e=>setCompanyName(e.detail.value??"")} /></IonItem></div><div className="form-grid"><SelectItem label="منبع" value={source} values={sources} labels={sourceLabels} onChange={setSource}/><SelectItem label="مرحله فروش" value={stage} values={Object.keys(stages)} labels={stages} onChange={value=>setStage(value as LeadStage)}/></div><IonItem className="form-item" lines="none"><IonLabel position="stacked">یادداشت</IonLabel><IonTextarea autoGrow value={notes} onIonInput={e=>setNotes(e.detail.value??"")} /></IonItem><IonButton className="primary-action" type="submit" expand="block" disabled={saving || !name.trim()}>{saving?<IonSpinner/>:"ثبت لید"}</IonButton></form></div></IonModal>;
}
function SelectItem({ label, value, values, labels, onChange }: { label:string; value:string; values:string[]; labels:Record<string,string>; onChange:(value:string)=>void }) { return <IonItem className="form-item" lines="none"><IonLabel position="stacked">{label}</IonLabel><IonSelect value={value} onIonChange={e=>onChange(String(e.detail.value))}>{values.map(item=><IonSelectOption key={item} value={item}>{labels[item] || item}</IonSelectOption>)}</IonSelect></IonItem>; }
function FollowUpModal({ lead, token, onDismiss, onSaved }: { lead?:Lead; token:string; onDismiss:()=>void; onSaved:(lead:Lead)=>void }) { const [dueAt,setDueAt]=useState(""); const [note,setNote]=useState(""); const [saving,setSaving]=useState(false); async function submit(e:React.FormEvent){e.preventDefault();if(!lead || !dueAt)return;setSaving(true);try{onSaved(await apiRequest<Lead>(`/leads/${recordId(lead)}/follow-ups`,{method:"POST",token,body:{dueAt:new Date(dueAt).toISOString(),note:note.trim()||undefined}}));setDueAt("");setNote("");}finally{setSaving(false);}} return <IonModal isOpen={Boolean(lead)} onDidDismiss={onDismiss} className="form-modal"><div className="modal-shell"><div className="modal-heading"><div><span className="page-eyebrow">FOLLOW-UP</span><h2>پیگیری {lead?.name}</h2></div><IonButton fill="clear" onClick={onDismiss}><IonIcon slot="icon-only" icon={closeOutline}/></IonButton></div><form className="modal-form" onSubmit={submit}><IonItem className="form-item" lines="none"><IonLabel position="stacked">زمان پیگیری</IonLabel><IonInput type="datetime-local" value={dueAt} onIonInput={e=>setDueAt(e.detail.value??"")} required/></IonItem><IonItem className="form-item" lines="none"><IonLabel position="stacked">توضیح</IonLabel><IonTextarea value={note} onIonInput={e=>setNote(e.detail.value??"")} autoGrow/></IonItem><IonButton className="primary-action" type="submit" expand="block" disabled={saving || !dueAt}>{saving?<IonSpinner/>:"ثبت پیگیری"}</IonButton></form></div></IonModal>; }
